resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/andreasholteritter/hello-world-pipe.git
    branch: master

jobs:
- name: job-build-and-verify
  plan:
    - get: git-repo
      trigger: true
    - task: build-and-verify
      file: git-repo/ci/mvn-build.yml